watch:
  directories:
    - app
    - tests
    - bootstrap
    - database
    - resources
    - routes
  fileMask: '*.php'
notifications:
  passingTests: false
  failingTests: false
phpunit:
  arguments: '--exclude external'
